### ISSUE TITLE
Not installable through OPAM on bytecode only switches

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#111]
But this is because of Menhir. See https://gitlab.inria.fr/fpottier/menhir/issues/19 for more information.

**Comment by treinen** [comment]
Hello, the issue against menhir has been fixed. Does this mean that this bug can be closed ?

**Comment by Niols** [comment]
https://github.com/colis-anr/morbig/pull/157 is evidence enough that the bug has, indeed, been fixed.
