### ISSUE TITLE
possible bug: unclosed subshell

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#12]
With morbig 20180209 I get an Unclosed Subshell error on the following input:

    #!/bin/sh
    
    f() {
        tempdir=`mktemp --directory --suffix=.aptlc`
    }

Seems that morbig does not like the "=" sign in the second option". -Ralf.

**Comment by Niols** [comment]
Hello,

Indeed, morbig seems to fail when encountering an equal symbol inside backquotes.
It does not seem to happen with `$(`. It happens both in assignment words and regular words.

**Comment by yurug** [comment]
Fixed by  84baa1a451aa9c1c6c9aaab86e6b0d18ee957227.
