### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by bfontaine** [colis-anr/morbig#14]
Hi there,
In https://github.com/colis-anr/morbig/commit/e9c90708fc64790f2abeb6021d289daa6fe2acdc you populated the `VERSION` file with "`0.1`". Does that mean this commit is the release 0.1? If so, would you mind adding a git tag?

    $ git tag 0.1 e9c90708fc64790f2abeb6021d289daa6fe2acdc
    $ git push --tags origin master

GitHub automatically generates tarballs for tags, so it’s easier to download a stable version instead of relying on the relative stableness of `HEAD`.

Thanks!

**Comment by yurug** [comment]
We are preparing the release and e9c9070 is step towards that path. But we are not there yet.

**Comment by bfontaine** [comment]
Thanks!
