### ISSUE TITLE
bad message in case of syntax error

### ISSUE THREAD

**Issue by claudemarche** [colis-anr/morbig#15]
When morbig encounters a syntactically incorrect file, it prints poorly informative
error messages such as `Fatal error: exception Libmorbig.Engine.ParseError` or  (a bit better) `Fatal error: exception Failure("Unclosed subshell (got '(').")`.

It should at least print the location of the error (line, character) and avoid talking about an « exception »

**Comment by yurug** [comment]
Fixed by 3ddd8748718383926d6ca791a0d2ea9114377e0b.
