### ISSUE TITLE
Alias with trailing space in replacement word

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#19]
The 2016 edition of the posix standard says:

> If the value of the alias replacing the word ends in a \<blank>, the shell shall check the next command word for alias substitution; this process shall continue until a word is found that is not a valid alias or an alias value does not end in a \<blank>.

I have absolutely no idea what does means (what is the "next command" ?), but there probably is a reason why this was written. We should try to find out what precisely this is supposed to mean.

**Comment by Niols** [comment]
En dash:

```
$ alias x='echo'
$ x x
x
$ alias x='echo '
$ x x
echo
```

**Comment by Niols** [comment]
From POSIX 2018, Shell & Utilities, 2.3.1 Alias Substitution:

> If the value of the alias replacing the word ends in a `<blank>`, the shell shall check the next command word for alias substitution; this process shall continue until a word is found that is not a valid alias or an alias value does not end in a `<blank>`.

In the example in my previous comment, the first alias for `x` does not end with a blank. In the simple command `x x`, only the first is replaced by `echo` and the substitution ends here, giving `echo x`. The second alias does end with a blank. The first substitution occurs and gives `echo x` but the substitution has to go on with the next token, giving `echo echo`.

**Comment by yurug** [comment]
Fixed by 3472358a65016bc87ad38320fa65a19412833bae.
