### ISSUE TITLE
Unknown error during script parse

### ISSUE THREAD

**Issue by anadon** [colis-anr/morbig#190]
I'm developing a tool at https://gitlab.com/anadon/detect_programs_called_from_script .

It is rough, but it just reached the point where it can compile and run.  The first test case I gave it was the following:

```
$ wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
$ ./_build/default/bin/main.exe < guix-install.sh
Fatal error: exception Morbig__Errors.DuringParsing(_)
```

I can't make anything of that and require assistance.

**Comment by anadon** [comment]
I think it is coming from `src/engine/ml:215`.

**Comment by anadon** [comment]
Identified the issue as lack of bash support.  Specifically, array support.

**Comment by Niols** [comment]
Indeed, that is correct; well spotted!
