### ISSUE TITLE
bad message in case of lexical error

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#20]
Issue #15 is fixed but that was only for syntax errors. The same should be done for lexical errors, for instance with the test cases from tests/bad/2.3_token-recognition:

% morbig unterminated-backquote.sh 
Fatal error: exception Prelexer.LexingError("Unterminated nesting!")

-Ralf.

**Comment by yurug** [comment]
Fixed 118bfc67b234c4f58a238911384b7b45dfdfdf70
