### ISSUE TITLE
build dependencies too strict

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#21]
README.mde says that one needs ocaml <= 4.04.2 to compile. However, it seems to compile and run without problems with ocaml 4.05.0. I sugest to drop the upper limit on the version of ocaml, unless there is compelling reason to keep it.

**Comment by Niols** [comment]
I agree. And if you look at [the results of the CI](https://travis-ci.org/colis-anr/morbig/builds/353844646), you can see that Morbig builds correctly with OCaml 4.05.0 and 4.06.0. And there is no real reason to think that it will change with other version of OCaml.

**Comment by Niols** [comment]
Since 16f85343d73c4cb9d93162c31f83d2d77e9a0216, we also test for 4.06.01, [and it works fine](https://travis-ci.org/colis-anr/morbig/builds/353938719).

**Comment by yurug** [comment]
As far as I remembered, I put this restriction because the opam package of one of our dependencies was not working. This seems fixed now, so yes, proceed!

**Comment by treinen** [comment]
fixed and closed.
