### ISSUE TITLE
Unable to match the ParseError exception when using Libmorbig

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#22]
When using Libmorbig and parsing a incorrect file, I get:

    Fatal error: exception Libmorbig.Errors.ParseError(_)

but when I try to `try ... match Libmorbig.Errors.ParseError _ -> ...`, I get `Error: Unbound module Libmorbig.Errors`.

**Comment by Niols** [comment]
In fact, the `SyntaxError` defined in `API` is used nowhere. And I can't really modify `parse_file` to raise it since `parse_file` is only defined in `Scripts` and that would create a circular dependency. I don't really know what would the right approach be, in that situation.

**Comment by yurug** [comment]
Fixed by 5abdb35
