### ISSUE TITLE
continuation lines in here documents

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#28]
when the delimiter word of a here document is not quoted, the symbol <backslash>behaves as inside
double quotes (standard 2.7.4). That is, <backslash><newline> indicates a continuation line. For instance
(test case continuation-line-in-here-documents):

```
if true
then
cat << EOF
first line
second line
third line with continuation\
EOF
forth and last line ((
EOF
else echo "baeh"
fi
```

the here document is ended in line 9, not line 7.

**Comment by treinen** [comment]
seems that the markdown processor has mangled my message. In the example input, there is a backslash at the end of "third line with continuation". The test case is also in the git.

**Comment by yurug** [comment]
Fixed.
