### ISSUE TITLE
What's the point of having the input filename in the "binary" output of Morbig?

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#31]
I don't really see the use case. In particular because it depends on where morbig has been called.

Is it really useful to have that in the marshalized value?

**Comment by yurug** [comment]
I guess it is not useful indeed since the user can define a external mapping from input filename to binary filename using the naming convention she wants.

Removing this is probably feasible but this will break tools like our statistics generator, right?

**Comment by Niols** [comment]
The statistical analyzer now redefines the export and import functions, so it wont be broken. Also, I think it could be nice to have the binary (de)serializer in the API.

**Comment by Niols** [comment]
@yurug I can also probably fix that myself. Do you want a PR?

**Comment by yurug** [comment]
Yes, please!

**Comment by yurug** [comment]
Ping @Niols?

**Comment by Niols** [comment]
Hello, sorry.

No, there is no PR. Essentially because I wanted to add API points like `save_as_binary` and `load_as_binary` in order to hide the Marshall mechanism and to provide the right type to the user.

And I wanted to wait for #29 to see what was the policy of the API: everything in `API.ml` or everything split up in several files (in which case, where should these save and load functions go?).
