### ISSUE TITLE
C inteface

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#49]
% cd examples/c/
    % make
    ocamlfind: Package `libmorbig' not found
    ocamlfind: Package `libmorbig' not found
    cc -o dump -I /usr/lib/ocaml -I  \
            dump.c -lm -ldl /libmorbigc.a
    cc: error: /libmorbigc.a: No such file or directory
    Makefile:7: recipe for target 'all' failed
    make: *** [all] Error 1

after changing in ```examples/c/Makefile``` all libmorbig to morbig:
 
    % make
     cc -o dump -I /usr/lib/ocaml -I /usr/local/lib/ocaml/4.02.3/morbig \
            dump.c -lm -ldl /usr/local/lib/ocaml/4.02.3/morbig/morbigc.a
     cc: error: /usr/local/lib/ocaml/4.02.3/morbig/morbigc.a: No such file or directory
     Makefile:7: recipe for target 'all' failed

**Comment by Niols** [comment]
Indeed. We left quite a lot of occurrences of "libmorbig" everywhere in the repository.
I'll take care of that

**Comment by Niols** [comment]
Hey @treinen, what about now?

**Comment by treinen** [comment]
OK, this is fixed now. Thanks!
