### ISSUE TITLE
Fatal error: exception Morbig.PrelexerState.NotAWord("OPERATOR(Semicolon)")

### ISSUE THREAD

**Issue by jwilk** [colis-anr/morbig#58]
This shell script

    echo ${1#;}

makes morbig die with fatal error:

    Fatal error: exception Morbig.PrelexerState.NotAWord("OPERATOR(Semicolon)")

As I understand it, `${1#;}` is not valid POSIX syntax (the semicolon should be quoted), even though the shells I tried don't seem to mind it.

Tested with git master (bb63f9e0297dcce321499e8e42b7ea31bbf056c3).

**Comment by Niols** [comment]
Hello, the same thing happens with the following words: `${bar#(}` and `${bar%)}` giving:

- `Fatal error: exception Morbig.PrelexerState.NotAWord("OPERATOR(Lparen)")`
- `Fatal error: exception Morbig.PrelexerState.NotAWord("OPERATOR(Rparen)")`

respectively.
