### ISSUE TITLE
not compiling on ubuntu and osx

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#59]
- [x] on Ubuntu because of `ld` for some reason that I don't understand
- [ ] on OSX because of the use of a GNU option of `ar`

**Comment by loganrosen** [comment]
I didn't mean to close this whole issue. @Niols, feel free to reopen it for the macOS issue.

**Comment by Niols** [comment]
Indeed, thank you very much for the Ubuntu fix btw!
