### ISSUE TITLE
bug: expansion in here documents

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#6]
from an anonymous reviewer:

Consider this shell script:

    cat <<'EOT'
    abc ` def
    ghi \
    jkl
    EOT
The delimiting word is quoted, so that the here-document lines should not be
expanded (§2.7.4). Morbig gives me a here-document containing "abc ` def\nghi
jkl\n". The backslash should have been included verbatim, not treated as
escaping the line break.

If I then put the same document inside a command substitution:

    x=$(cat <<'EOT'
    abc ` def
    ghi \
    jkl
    EOT
    )
then I get an error "Lexing error: unbalanced parentheses". Removing or escaping
the backtick removes the error, but being inside a command substitution should
not change the parsing of here-documents (Per §2.6.3, "Any valid shell script
can be used for *command*"). The given word is then "$(cat <<'EOT' abc \\` def
ghi jkl EOT )", which is missing **all** of the newlines - I'm not sure whether
that's presentational or another difference.

**Comment by yurug** [comment]
First bug fixed by 46d2329469333bd8b1cef0e9ed42a2f8e3983cc7.

**Comment by yurug** [comment]
Second bug fixed by ea65f90cf644cb1a6af50404650fa53e41e8e973.
