### ISSUE TITLE
Rename `Morbig.API` → `Morbig`?

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#64]
Now that we compile with Dune, it's super easy to make all the functions of API directly accessible from the `Morbig` module. `Morbig.API.parse_file` would simply be `Morbig.parse_file`. The other modules would still be accessible naturally (`Morbig.CST.program`, for instance).

This can be a breaking change. Actually, this can also be done in a retro-compatible way (by providing access to this functions both directly in the `Morbig` module and in the `Morbig.API` module) but I'd rather take advantage of the fact that we are preparing breaking changes anyway to do this one.

I would personally vote for that and it's a matter of minutes (if not seconds) for me to do this change. What do you think, @treinen, @yurug?

**Comment by treinen** [comment]
Sounds good to me.

**Comment by yurug** [comment]
Please proceed!
