### ISSUE TITLE
parsing of here documents

### ISSUE THREAD

**Issue by treinen** [colis-anr/morbig#75]
the CST of a here document is a word,  with an empty CST. Shouldn't the contents of a "normal" here-document be word-parsed, as it is the case now for other words ? By "normal here-document" I mean a here-document where the defining occurrence of the delimiter is not quoted. If the delimiter is quoted then the contents of the here-document should just be a WordLiteral since in that case no expansion shall happen on the contents of the here document.

**Comment by Niols** [comment]
I agree, they should be parsed. Except if there is a counter-indication for this?

**Comment by yurug** [comment]
I agree. Thanks for reporting.

**Comment by yurug** [comment]
Fixed a long time again.
