### ISSUE TITLE
Assert failure when parsing Git conflicts

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#76]
Try running Morbig on:

```
<<<<<<< HEAD
foo
=======
bar
>>>>>>> master
```

You'll get:

```
Fatal error: exception File "src/hereDocument.ml", line 70, characters 4-10: Assertion failed
```

while Dash goes:

```
Syntax error: redirection unexpected
```

It's not an issue to reject this script. It is one not to fail gracefully.

**Comment by treinen** [comment]
the question is whether the standard allows  a word starting on "<<" as a delimiter for a here document.

**Comment by treinen** [comment]
If I read correctly section 2.3 of the standard ("token recognition"), reading two < signs results in
emitting a token for the operator DLESS, and then continues scanning the rest.
