### ISSUE TITLE
Morbig accepts `if ... then` without separator. And the standard seems to agree.

### ISSUE THREAD

**Issue by Niols** [colis-anr/morbig#87]
I am not sure if this is a bug in Morbig, but Morbig accepts:

```sh
if foo then
   bar
fi
```

which to me was invalid. Dash and Bash tend to agree with that and refuse the script, saying respectively:

```
test.sh: 3: test.sh: Syntax error: "fi" unexpected (expecting "then")
```

and

```
test.sh: ligne 3: erreur de syntaxe près du symbole inattendu « fi »
test.sh: ligne 3: `fi'
```

However, when reading the standard, it seems to me that this is indeed an acceptable script and that no separator is required before the `then` word. Is that an issue for dash/bash? Should we ask for clarification to the POSIX mailing-list, because the usage clearly seems to disagree with the standard?

**Comment by Niols** [comment]
Actually, no, the standard disagrees, I believe. This is coming from the rule 1 in the grammar:

> [Command Name]
> 
> When the TOKEN is exactly a reserved word, the token identifier for that reserved word shall result. Otherwise, the token WORD shall be returned. Also, if the parser is in any state where only a reserved word could be the next correct token, proceed as above.
> 
> Note:
> Because at this point <quotation-mark\> characters are retained in the token, quoted strings cannot be recognized as reserved words. This rule also implies that reserved words are not recognized except in certain positions in the input, such as after a <newline\> or <semicolon\>; the grammar presumes that if the reserved word is intended, it is properly delimited by the user, and does not attempt to reflect that requirement directly. Also note that line joining is done before tokenization, as described in Escape Character (Backslash), so escaped <newline\> characters are already removed at this point.
>
> Rule 1 is not directly referenced in the grammar, but is referred to by other rules, or applies globally.

**Comment by Niols** [comment]
Also, not that `}` is considered a reserved keyword in that setting. Meaning that:

```sh
{ echo foo }
```

should be rejected as well.

**Comment by yurug** [comment]
The specification seems highly ambiguous to me: the note seems to contradict the sentence "Also, if the parser is in any state where only a reserved word could be the next correct token, proceed as above." which is followed by morbig.

**Comment by Niols** [comment]
I remember that we discussed with people on the POSIX mailing list. The answer seemed to be that the separator was mandatory. Although I agree with you that the specification couldn't be more ambiguous.

**Comment by Niols** [comment]
My bad. I though I could still reproduce but I wasn't fully up to date.

**Comment by Niols** [comment]
The issue is still there with `fi`.
